//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accession()
        {
            this.LisCases = new HashSet<LisCase>();
        }
    
        public int AccessionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string BillTypeName { get; set; }
        public string ReasonForReferral { get; set; }
        public string ClinicalData { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> OrderDate { get; set; }
        public Nullable<System.DateTimeOffset> CompletedDate { get; set; }
        public string ClinicalHistory { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string RequisitionNumber { get; set; }
        public Nullable<int> OrderingPhysician { get; set; }
        public Nullable<int> RenderingPhysician { get; set; }
        public string Deficiencies { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public byte FlagForReview { get; set; }
        public Nullable<int> LabId { get; set; }
        public Nullable<System.DateTimeOffset> LastCompletedDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LisCase> LisCases { get; set; }
    }
}
