//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseErrorReport
    {
        public string CaseNumber { get; set; }
        public string ErrorType { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
