//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CELHeaderInfo
    {
        public int id { get; set; }
        public string FileName { get; set; }
        public string CaseNumber { get; set; }
        public string CaseNumberQualifier { get; set; }
        public string ScanDate { get; set; }
        public System.DateTimeOffset ParseDate { get; set; }
        public string FileTypeIdentifier { get; set; }
        public string AlgorithmName { get; set; }
        public string ArrayType { get; set; }
        public string ScannerId { get; set; }
        public string FluidicsStationID { get; set; }
        public string FluidicsModuleID { get; set; }
        public string FileIdentifier { get; set; }
        public string ScannerOperator { get; set; }
        public string FileCreator { get; set; }
        public string UploaderID { get; set; }
        public string UploaderWorkEnvironment { get; set; }
        public string OriginalCELFilePath { get; set; }
        public string CELFilename { get; set; }
        public Nullable<System.DateTime> ResultsCreationDate { get; set; }
        public string ArrayBarCode { get; set; }
        public Nullable<System.DateTime> QCCreationDate { get; set; }
        public Nullable<int> StudyId { get; set; }
        public Nullable<System.DateTime> CELFileCreationDate { get; set; }
        public Nullable<System.DateTime> CELFileModifiedDate { get; set; }
    }
}
