//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LisCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LisCase()
        {
            this.PatientInsurances = new HashSet<PatientInsurance>();
        }
    
        public int id { get; set; }
        public int AccessionId { get; set; }
        public bool isActive { get; set; }
        public Nullable<bool> isRescan { get; set; }
        public string RescanCaseNumber { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<System.DateTime> DateofService { get; set; }
        public string DiagnosisCode { get; set; }
        public string ICD9Codes { get; set; }
        public string ICD10Codes { get; set; }
        public string ComputedICD10Codes { get; set; }
        public string ICD10Source { get; set; }
        public Nullable<int> LabId { get; set; }
        public string PRS { get; set; }
        public int PayorId1 { get; set; }
        public int PayorId2 { get; set; }
        public string QNS { get; set; }
        public string QNSReason { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public string SubGroupDesignation { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public byte FlagForReview { get; set; }
        public System.DateTimeOffset LastCaseEdit { get; set; }
        public string LastCaseEditUser { get; set; }
        public Nullable<System.DateTimeOffset> CompletedDate { get; set; }
        public Nullable<System.DateTimeOffset> LastCompletedDate { get; set; }
        public string WorkflowStep { get; set; }
    
        public virtual Accession Accession { get; set; }
        public virtual Payor Payor { get; set; }
        public virtual Payor Payor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientInsurance> PatientInsurances { get; set; }
    }
}
