//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInsurance
    {
        public int CaseId { get; set; }
        public string CaseNumber { get; set; }
        public int Rank { get; set; }
        public string InsuredRelationship { get; set; }
        public string SubscriberFirstName { get; set; }
        public string SubscriberLastName { get; set; }
        public string SubscriberMiddleName { get; set; }
        public string SubscriberGender { get; set; }
        public Nullable<System.DateTime> SubscriberDateOfBirth { get; set; }
        public string SubscriberAddress1 { get; set; }
        public string SubscriberAddress2 { get; set; }
        public string SubscriberCity { get; set; }
        public string SubscriberStateProvince { get; set; }
        public string SubscriberCountry { get; set; }
        public string SubscriberPostalCode { get; set; }
        public string SubscriberPhoneNumber { get; set; }
        public string HomePlan { get; set; }
        public string PlanType { get; set; }
        public string PolicyNumber { get; set; }
        public string GroupNumber { get; set; }
        public string AuthorizationNumber { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public string PayorNetwork1 { get; set; }
        public string PayorNetwork2 { get; set; }
    
        public virtual LisCase LisCase { get; set; }
    }
}
