//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.SGNL_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_apiGetBillingCases
    {
        public Nullable<bool> Billable { get; set; }
        public string BillingTestType { get; set; }
        public string Cancelled { get; set; }
        public string CancelledReason { get; set; }
        public string BillType { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTimeOffset> CompletedDate { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTime> DateofService { get; set; }
        public string Deficiencies { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string ICD9Codes { get; set; }
        public string ICD10Codes { get; set; }
        public string ComputedICD10Codes { get; set; }
        public string ICD10Source { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string InsuranceCompanyName1 { get; set; }
        public string InsuranceCompanyName2 { get; set; }
        public string MRN { get; set; }
        public Nullable<System.DateTimeOffset> OrderedDate { get; set; }
        public string OrderingPhysician { get; set; }
        public string OrderingPhysicianNpi { get; set; }
        public string PatientFirstName { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string PatientLastName { get; set; }
        public string PatientMiddleName { get; set; }
        public string PatientSex { get; set; }
        public string PatientStatus { get; set; }
        public string PatientAddress1 { get; set; }
        public string PatientAddress2 { get; set; }
        public string PatientCity { get; set; }
        public string PatientState { get; set; }
        public string PatientPostalCode { get; set; }
        public string PayorCode { get; set; }
        public string PlaceOfService { get; set; }
        public string PayorCode2 { get; set; }
        public string PlaceOfService2 { get; set; }
        public Nullable<int> PayorID { get; set; }
        public Nullable<int> PayorID2 { get; set; }
        public string QNS { get; set; }
        public string QNSReason { get; set; }
        public Nullable<int> RepeatCount { get; set; }
        public string SpecimenType { get; set; }
        public int IsActive { get; set; }
    }
}
