//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_Case
    {
        public string CaseNo { get; set; }
        public int AccessionId { get; set; }
        public Nullable<int> FacilityID { get; set; }
        public Nullable<int> LabID { get; set; }
        public string CaseTypeName { get; set; }
        public string ClientCaseNo { get; set; }
        public string TreatingPhysician { get; set; }
        public string CLIANumber { get; set; }
        public string CLIAName { get; set; }
        public string CLIAAddress1 { get; set; }
        public string CLIAAddress2 { get; set; }
        public string CLIAAddress3 { get; set; }
        public string CLIACity { get; set; }
        public string CLIAStateProvince { get; set; }
        public string CLIACountry { get; set; }
        public string CLIAPostalCode { get; set; }
        public string WorkflowStep { get; set; }
        public string QNSReason { get; set; }
        public Nullable<int> OriginalAccessionId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool isActive { get; set; }
        public bool isUpdated { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> LastCompletedDate { get; set; }
    
        public virtual XIFIN_Labs XIFIN_Labs { get; set; }
    }
}
