//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_LabMessage
    {
        public string id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EventType { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
