//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_LabMessage_Case
    {
        public int id { get; set; }
        public System.Guid GUID { get; set; }
        public int AccessionId { get; set; }
        public string CaseNumber { get; set; }
        public System.DateTime ReceiveUTCDate { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public string EventType { get; set; }
    
        public virtual XIFIN_Accession XIFIN_Accession { get; set; }
    }
}
