//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_CaseInsurance
    {
        public Nullable<int> InsuranceId { get; set; }
        public string InsuranceCode { get; set; }
        public string CaseNo { get; set; }
        public string PayorId { get; set; }
        public int PayorRank { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
