//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_TestOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XIFIN_TestOrder()
        {
            this.XIFIN_ICD9 = new HashSet<XIFIN_ICD9>();
            this.XIFIN_Result = new HashSet<XIFIN_Result>();
            this.XIFIN_TestOrderSpecimen = new HashSet<XIFIN_TestOrderSpecimen>();
            this.XIFIN_ICD10 = new HashSet<XIFIN_ICD10>();
        }
    
        public int TestOrderID { get; set; }
        public string CaseNo { get; set; }
        public string TestCode { get; set; }
        public string TestName { get; set; }
        public string PanelName { get; set; }
        public string TestTypeName { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XIFIN_ICD9> XIFIN_ICD9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XIFIN_Result> XIFIN_Result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XIFIN_TestOrderSpecimen> XIFIN_TestOrderSpecimen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XIFIN_ICD10> XIFIN_ICD10 { get; set; }
    }
}
