//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_Accession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XIFIN_Accession()
        {
            this.XIFIN_LabMessage_Case = new HashSet<XIFIN_LabMessage_Case>();
        }
    
        public string LabMessageId { get; set; }
        public int AccessionId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string ExternalAccessionID { get; set; }
        public string BillTypeName { get; set; }
        public string ReasonForReferral { get; set; }
        public string ClinicalData { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ClinicalHistory { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public string RequisitionNumber { get; set; }
        public Nullable<int> OrderingPhysician { get; set; }
        public Nullable<int> RenderingPhysician { get; set; }
        public string Deficiencies { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> LabId { get; set; }
        public Nullable<System.DateTime> LastCompletedDate { get; set; }
        public string Destination { get; set; }
    
        public virtual XIFIN_Client XIFIN_Client { get; set; }
        public virtual XIFIN_Doctor XIFIN_Doctor { get; set; }
        public virtual XIFIN_Facility XIFIN_Facility { get; set; }
        public virtual XIFIN_Patient XIFIN_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XIFIN_LabMessage_Case> XIFIN_LabMessage_Case { get; set; }
    }
}
