//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_PatientInsurance
    {
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> InsuranceId { get; set; }
        public string CaseNo { get; set; }
        public string InsuranceName { get; set; }
        public int Rank { get; set; }
        public string HomePlan { get; set; }
        public string PayorGroup { get; set; }
        public string PlanType { get; set; }
        public string SubscriberFirstName { get; set; }
        public string SubscriberLastName { get; set; }
        public string SubscriberMiddleName { get; set; }
        public string SubscriberGender { get; set; }
        public string SubscriberSocialSecurityNo { get; set; }
        public Nullable<System.DateTime> SubscriberDateOfBirth { get; set; }
        public string SubscriberAddress1 { get; set; }
        public string SubscriberAddress2 { get; set; }
        public string SubscriberAddress3 { get; set; }
        public string SubscriberCity { get; set; }
        public string SubscriberStateProvince { get; set; }
        public string SubscriberCountry { get; set; }
        public string SubscriberPostalCode { get; set; }
        public string SubscriberPhoneNumber { get; set; }
        public string PatientRelation { get; set; }
        public string PolicyNo { get; set; }
        public string GroupNo { get; set; }
        public string AuthorizationNo { get; set; }
        public string InsuranceCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
