//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_Phone
    {
        public int id { get; set; }
        public string Category { get; set; }
        public string PhoneId { get; set; }
        public string PhoneType { get; set; }
        public string PhoneNumber { get; set; }
        public string Extension { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
