//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XifinLISEntities : DbContext
    {
        public XifinLISEntities()
            : base("name=XifinLISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<XIFIN_Accession> XIFIN_Accession { get; set; }
        public virtual DbSet<XIFIN_Address> XIFIN_Address { get; set; }
        public virtual DbSet<XIFIN_Case> XIFIN_Case { get; set; }
        public virtual DbSet<XIFIN_CaseInsurance> XIFIN_CaseInsurance { get; set; }
        public virtual DbSet<XIFIN_Client> XIFIN_Client { get; set; }
        public virtual DbSet<XIFIN_Doctor> XIFIN_Doctor { get; set; }
        public virtual DbSet<XIFIN_DoctorIdentification> XIFIN_DoctorIdentification { get; set; }
        public virtual DbSet<XIFIN_Facility> XIFIN_Facility { get; set; }
        public virtual DbSet<XIFIN_ICD9> XIFIN_ICD9 { get; set; }
        public virtual DbSet<XIFIN_LabMessage> XIFIN_LabMessage { get; set; }
        public virtual DbSet<XIFIN_Labs> XIFIN_Labs { get; set; }
        public virtual DbSet<XIFIN_Patient> XIFIN_Patient { get; set; }
        public virtual DbSet<XIFIN_PatientInsurance> XIFIN_PatientInsurance { get; set; }
        public virtual DbSet<XIFIN_Phone> XIFIN_Phone { get; set; }
        public virtual DbSet<XIFIN_Report> XIFIN_Report { get; set; }
        public virtual DbSet<XIFIN_Result> XIFIN_Result { get; set; }
        public virtual DbSet<XIFIN_Specimen> XIFIN_Specimen { get; set; }
        public virtual DbSet<XIFIN_TestOrder> XIFIN_TestOrder { get; set; }
        public virtual DbSet<XIFIN_TestOrderSpecimen> XIFIN_TestOrderSpecimen { get; set; }
        public virtual DbSet<XIFIN_ICD10> XIFIN_ICD10 { get; set; }
        public virtual DbSet<XIFIN_LabMessage_Case> XIFIN_LabMessage_Case { get; set; }
    }
}
