//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonTools.EFDataModel.XIFIN_LIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class XIFIN_Report
    {
        public string CaseNo { get; set; }
        public int Version { get; set; }
        public string VersionTypeName { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
        public Nullable<int> SignedUserId { get; set; }
        public string SignedUserFirstName { get; set; }
        public string SignedUserLastName { get; set; }
        public string ReportTypeName { get; set; }
        public Nullable<int> ReportTemplateId { get; set; }
        public string ReportTemplateName { get; set; }
        public string DocumentName { get; set; }
        public byte[] Document { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string MyPRSRiskScore { get; set; }
        public string MyPRSRiskClassification { get; set; }
        public string PatientSubtype { get; set; }
        public string ReportComment { get; set; }
    }
}
